apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: savr-api-ingress
  namespace: {{ .Values.name }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.name }}.theswamp.cloud
    secretName: {{ .Values.name }}-tls
  rules:
  - host: {{ .Values.name }}.theswamp.cloud
    http:
      paths:
      - backend:
          service:
            name: savr-api-deployment
            port:
              number: 8080
        path: /
        pathType: Prefix
