apiVersion: batch/v1
kind: Job
metadata:
  name: retriever-init
  namespace: {{ .Values.name }}
spec:
  template:
    spec:
      metadata:
        labels:
          date: "{{ now | unixEpoch }}"
      containers:
      - name: retriever-init
        image: tenebresus/savr-retriever:latest
        imagePullPolicy: Always
      restartPolicy: OnFailure
      initContainers:
      - name: init
        image: alpine
        command: ["/bin/sh", "-c", "sleep 20"]
