apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: savr-api-deployment
  name: savr-api-deployment
  namespace: {{ .Values.name }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: savr-api-deployment
status:
  loadBalancer: {}
