package lidl

type LidlT struct {
	HavingVideos             bool  `json:"havingVideos"`
	AlcoholicDetails         any   `json:"alcoholicDetails"`
	Promoted                 any   `json:"promoted"`
	EnergyLabelSelectVariant any   `json:"energyLabelSelectVariant"`
	ListID                   int   `json:"listId"`
	HighlightedSeals         int   `json:"highlightedSeals"`
	SpecialDesc              any   `json:"specialDesc"`
	Seals                    []any `json:"seals"`
	Price                    struct {
		Price    float64 `json:"price"`
		HasVat   bool    `json:"hasVat"`
		Prefix   any     `json:"prefix"`
		EndDate  any     `json:"endDate"`
		HasStar  bool    `json:"hasStar"`
		Discount struct {
			Suffix               any    `json:"suffix"`
			EndDate              any    `json:"endDate"`
			ShowFrom             bool   `json:"showFrom"`
			ShowUpTo             bool   `json:"showUpTo"`
			DeletedPrice         any    `json:"deletedPrice"`
			DiscountText         string `json:"discountText"`
			ShowDiscount         bool   `json:"showDiscount"`
			DiscountTitle        string `json:"discountTitle"`
			ShowPercentage       bool   `json:"showPercentage"`
			DiscountHasStar      bool   `json:"discountHasStar"`
			DeletedPriceSecond   any    `json:"deletedPriceSecond"`
			PercentageDiscount   any    `json:"percentageDiscount"`
			FromRecommendedPrice bool   `json:"fromRecommendedPrice"`
		} `json:"discount"`
		OldPrice                    int    `json:"oldPrice"`
		BasePrice                   any    `json:"basePrice"`
		Packaging                   any    `json:"packaging"`
		PriceTheme                  string `json:"priceTheme"`
		PriceSecond                 any    `json:"priceSecond"`
		Superscript                 any    `json:"superscript"`
		CurrencyCode                string `json:"currencyCode"`
		SpecialTaxes                []any  `json:"specialTaxes"`
		CurrencySymbol              string `json:"currencySymbol"`
		OldPriceSecond              any    `json:"oldPriceSecond"`
		DrainWeightPrice            any    `json:"drainWeightPrice"`
		RecommendedPrice            any    `json:"recommendedPrice"`
		SalesStaggerings            any    `json:"salesStaggerings"`
		DisplayedCurrency           any    `json:"displayedCurrency"`
		CurrencyCodeSecond          string `json:"currencyCodeSecond"`
		CurrencySymbolSecond        string `json:"currencySymbolSecond"`
		DisplayedCurrencySecond     any    `json:"displayedCurrencySecond"`
		MultipackDisplayedCurrency  any    `json:"multipackDisplayedCurrency"`
		VariantsHaveDifferentPrices bool   `json:"variantsHaveDifferentPrices"`
	} `json:"price"`
	HavingThreesixty bool  `json:"havingThreesixty"`
	CampaignInfo     any   `json:"campaignInfo"`
	Ribbons          []any `json:"ribbons"`
	DealOfDay        struct {
		Active            bool `json:"active"`
		EndTime           any  `json:"endTime"`
		StartTime         any  `json:"startTime"`
		Translations      any  `json:"translations"`
		NewsletterURL     any  `json:"newsletterUrl"`
		CampaignPriceType any  `json:"campaignPriceType"`
	} `json:"dealOfDay"`
	VariantID any `json:"variantId"`
	Brand     struct {
		ID        any  `json:"id"`
		URL       any  `json:"url"`
		Logo      any  `json:"logo"`
		Name      any  `json:"name"`
		ShowBrand bool `json:"showBrand"`
	} `json:"brand"`
	SpecialDescTheme any    `json:"specialDescTheme"`
	Image            string `json:"image"`
	ProductID        int    `json:"productId"`
	RenderedTs       int    `json:"renderedTs"`
	Keyfacts         struct {
		Seals                   any    `json:"seals"`
		Title                   string `json:"title"`
		ColorSets               any    `json:"colorSets"`
		FullTitle               string `json:"fullTitle"`
		Description             any    `json:"description"`
		MoreDetails             string `json:"moreDetails"`
		TextileSizes            any    `json:"textileSizes"`
		TitleSuperscript        any    `json:"titleSuperscript"`
		AnalyticsCategory       string `json:"analyticsCategory"`
		SupplementalDescription any    `json:"supplementalDescription"`
	} `json:"keyfacts"`
	VariantImages       any      `json:"variantImages"`
	ItemID              int      `json:"itemId"`
	ErpNumber           string   `json:"erpNumber"`
	AdvertisementID     any      `json:"advertisementId"`
	SalesAttributes     any      `json:"salesAttributes"`
	Gs1Attributes       []any    `json:"gs1Attributes"`
	PreventSelling      bool     `json:"preventSelling"`
	CanonicalPath       string   `json:"canonicalPath"`
	DesignTheme         string   `json:"designTheme"`
	ImageList           []string `json:"imageList"`
	DisplayFreeDelivery bool     `json:"displayFreeDelivery"`
	Regions             []any    `json:"regions"`
	Cutoutimage         struct {
		LargeURL  any `json:"largeUrl"`
		SmallURL  any `json:"smallUrl"`
		MediumURL any `json:"mediumUrl"`
	} `json:"cutoutimage"`
	Multipack     bool   `json:"multipack"`
	EnergyLabels  []any  `json:"energyLabels"`
	ProductOrigin any    `json:"productOrigin"`
	Title         string `json:"title"`
	Disclaimers   []struct {
		ID     string `json:"id"`
		Type   string `json:"type"`
		Value  string `json:"value"`
		Prefix any    `json:"prefix"`
	} `json:"disclaimers"`
	MouseoverImage        any      `json:"mouseoverImage"`
	HavingPrice           bool     `json:"havingPrice"`
	Ratings               any      `json:"ratings"`
	LidlPlus              []any    `json:"lidlPlus"`
	SetItemQuantity       any      `json:"setItemQuantity"`
	IsUsedProduct         bool     `json:"isUsedProduct"`
	ProductType           string   `json:"productType"`
	FullTitle             string   `json:"fullTitle"`
	CanonicalURL          string   `json:"canonicalUrl"`
	Store                 bool     `json:"store"`
	FlashSales            bool     `json:"flashSales"`
	Ians                  []string `json:"ians"`
	ParentID              any      `json:"parentId"`
	QuickAddToCart        bool     `json:"quickAddToCart"`
	GridLabel             any      `json:"gridLabel"`
	CategorySecondaryPath any      `json:"categorySecondaryPath"`
	Awards                []any    `json:"awards"`
	VariantGroupID        any      `json:"variantGroupId"`
	HavingVariablePrices  bool     `json:"havingVariablePrices"`
	Online                bool     `json:"online"`
	AgeRestriction        bool     `json:"ageRestriction"`
	ListName              string   `json:"listName"`
	Category              string   `json:"category"`
	AttributesCode        any      `json:"attributesCode"`
	StockAvailability     struct {
		BadgeInfo struct {
			Badges []struct {
				Text             string `json:"text"`
				Type             string `json:"type"`
				DeliveryInfoText any    `json:"deliveryInfoText"`
			} `json:"badges"`
		} `json:"badgeInfo"`
		BackInStockInfo                any   `json:"backInStockInfo"`
		OnlineAvailable                bool  `json:"onlineAvailable"`
		OrderableQuantities            []any `json:"orderableQuantities"`
		PreselectedQuantity            any   `json:"preselectedQuantity"`
		MinOrderableQuantity           int   `json:"minOrderableQuantity"`
		AvailabilityIndicator          int   `json:"availabilityIndicator"`
		BackInStockNotification        any   `json:"backInStockNotification"`
		InitialMinOrderableQuantity    any   `json:"initialMinOrderableQuantity"`
		BackInStockNotificationSoldOut any   `json:"backInStockNotificationSoldOut"`
	} `json:"stockAvailability"`
	Position                    string `json:"position"`
	AdditionalHighlightProducts any    `json:"additionalHighlightProducts"`
}
