name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

    - name: Build the savr API image
      run: docker buildx build --push -t tenebresus/savr-api --platform linux/amd64,linux/arm/v7,linux/arm64 --build-arg CMD=api .

    - name: Build the savr retriever image
      run: docker buildx build --push -t tenebresus/savr-retriever --platform linux/amd64,linux/arm/v7,linux/arm64 --build-arg CMD=retriever .
