name: Deploy with Helm

on:

  pull_request:
    branches:
      - main
    types: [closed]

  workflow_run:
    workflows: ["Docker Image CI"]  # Triggers after this workflow completes
    types:
      - completed  # Runs only when the workflow is completed

  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository on same branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Get current Git ref
        run: echo "GIT_REF=$(git rev-parse --symbolic-full-name HEAD)" >> $GITHUB_ENV

      - name: Set up Kubernetes
        run: |
          mkdir $HOME/.kube; echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Set Helm values based on branch
        run: |
          if [[ "${{ env.GIT_REF }}" == "refs/heads/develop" ]]; then
            echo "HELM_VALUES=dev-savr --set name=dev-savr ./deploy/helm" >> $GITHUB_ENV
          elif [[ "${{ env.GIT_REF }}" == "refs/heads/main" ]]; then
            echo "HELM_VALUES=savr ./deploy/helm" >> $GITHUB_ENV
          fi

      - name: Deploy using Helm
        run: |
          helm upgrade --install ${{ env.HELM_VALUES }}
